---
- name: Call the playbook run from bastion node to failover the EDB cluster to Site 2 as the primary.
  hosts: all
  gather_facts: false
  tasks:
    - name: Failover EDB cluster to Site 2 as primary/leader.
      ansible.builtin.shell:
        cmd: tpaexec playbook "{{ edb_cluster }}" /opt/EDB/TPA/architectures/M1/commands/switchover.yml -e "target={{ site_two_db }}"
        chdir: /home/rhel/
