kind: Secret
apiVersion: v1
metadata:
  name: aap-26-eda-db-fields-encryption-secret
  namespace: "{{ namespace_site_one }}"
stringData:
  secret_key: "{{ aap_eda_db_fields_encryption_key }}"
type: Opaque
