kind: Secret
apiVersion: v1
metadata:
  name: aap-26-automationhub-db-fields-encryption
  namespace: "{{ namespace_site_one }}"
data:
  database_fields.symmetric.key: "{{ automationhub_db_fields_encryption_key }}"
type: Opaque