---
apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  name: aap-26
  namespace: "{{ namespace_site_one }}"
spec:
  route_tls_termination_mechanism: Edge
  no_log: true
  redis_mode: cluster
  image_pull_policy: Always
  api:
    log_level: INFO
    replicas: 1
  database:
    postgres_data_volume_init: false
    database_secret: external-postgres-configuration-gateway
    disabled: false
  controller:
    name: aap-26-controller
     postgres_configuration_secret: external-postgres-configuration-controller
  hub:
    name: aap-26-automationhub
    postgres_configuration_secret: external-postgres-configuration-hub
  eda:
    name: aap-26-eda
    database:
      database_secret: external-postgres-configuration-eda
  lightspeed: 
    disabled: true