---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ _hub_file_storage_pv_site }}"
spec:
  capacity:
    storage: "{{ hub_file_storage_size }}"
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "{{ hub_file_storage_nfs_server }}"
    path: "{{ hub_file_storage_nfs_path }}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ (aap_instance_name | default('aap-26')) ~ '-hub-file-storage' }}"
  namespace: "{{ namespace_site_one }}"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "{{ hub_file_storage_size }}"
  volumeName: "{{ _hub_file_storage_pv_site }}"
  storageClassName: ""
