kind: Secret
apiVersion: v1
metadata:
  name: external-postgres-configuration-hub
  namespace: aap-26
data:
  database: "{{ db_name_hub }}"
  host: "{{ db_host_site_one }}"
  password: "{{ db_password_hub }}"
  port: "{{ db_port }}"
  sslmode: "{{ db_sslmode }}"
  type: unmanaged
  username: "{{ db_username_hub }}"
type: Opaque