---
kind: Secret
apiVersion: v1
metadata:
  name: external-postgres-configuration-gateway
  namespace: "{{ namespace_site_one }}"
stringData:
  database: "{{ db_name_gateway }}"
  host: "{{ db_host_site_one }}"
  password: "{{ db_password_gateway }}"
  port: "{{ db_port }}"
  sslmode: "{{ db_sslmode }}"
  type: unmanaged
  username: "{{ db_username_gateway }}"
type: Opaque
