- name: Scale AAP Controller to desired state.
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Scale AAP Controller CR replicas according to role. 
      redhat.openshift.k8s:
        state: present
        api_version: eda.ansible.com/v1alpha1
        kind: EDA
        name: "{{ eda_cr_name }}"
        namespace: "{{ eda_cr_namespace }}"
        merge_type: merge 
        definition:
          spec:
            event_stream:  
              replicas: "{{ desired_replicas }}"
