- name: Scale AAP Controller to desired state.
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Scale AAP Controller CR replicas according to role. 
      redhat.openshift.k8s:
        state: present
        api_version: automationcontroller.ansible.com/v1beta1
        kind: AutomationController
        name: "{{ controller_cr_name }}"
        namespace: "{{ controller_cr_namespace }}"
        merge_type: merge 
        definition:
          spec:
            replicas: "{{ desired_replicas }}"
