- name: Scale AAP Hub accordingly.
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Scale Hub CR replicas according to role. 
      redhat.openshift.k8s:
        state: present
        api_version: automationhub.ansible.com/v1beta1
        kind: AutomationHub
        name: "{{ hub_cr_name }}"
        namespace: "{{ hub_cr_namespace }}"
        merge_type: merge 
        definition:
          spec:
            web:
              replicas: "{{ web_desired_replicas }}"
            content:
              replicas: "{{ content_desired_replicas }}"
            api: 
              replicas: "{{ api_desired_replicas }}"
            redis: 
              replicas: "{{ redis_desired_replicas }}"
            worker: 
              replicas: "{{ worker_desired_replicas }}"
