---
apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  name: "{{ aap_instance_name | default('aap-26') }}"
  namespace: "{{ namespace_site_two }}"
spec:
  route_tls_termination_mechanism: Edge
  no_log: true
  redis_mode: cluster
  image_pull_policy: Always
  api:
    log_level: INFO
    replicas: 1
  database:
    postgres_data_volume_init: false
    database_secret: external-postgres-configuration-gateway
    disabled: false
  controller:
    name: aap-26-controller
    postgres_configuration_secret: external-postgres-configuration-controller
  hub:
    postgres_configuration_secret: external-postgres-configuration-hub
    name: aap-26-automationhub
{% if hub_content_storage_type | default('') == 's3' %}
    storage_type: S3
    object_storage_s3_secret: "{{ hub_object_storage_secret_name }}"
{% elif hub_content_storage_type | default('') == 'azure' %}
    storage_type: azure
    object_storage_azure_secret: "{{ hub_object_storage_secret_name }}"
{% elif hub_content_storage_type | default('') == 'file' %}
    storage_type: file
{% if hub_file_storage_provisioning | default('dynamic') == 'static_nfs' %}
    file_storage_size: "{{ hub_file_storage_size }}"
{% else %}
    file_storage_storage_class: "{{ hub_file_storage_storage_class }}"
    file_storage_size: "{{ hub_file_storage_size }}"
{% endif %}
{% endif %}
  eda:
    database:
      database_secret: external-postgres-configuration-eda
    name: aap-26-eda
  lightspeed: 
    disabled: true