kind: Secret
apiVersion: v1
metadata:
  name: external-postgres-configuration-hub
  namespace: "{{ namespace_site_two }}"
stringData:
  database: "{{ db_name_hub }}"
  host: "{{ db_host_site_two }}"
  password: "{{ db_password_hub }}"
  port: "{{ db_port }}"
  sslmode: "{{ db_sslmode }}"
  type: unmanaged
  username: "{{ db_username_hub }}"
type: Opaque