kind: Secret
apiVersion: v1
metadata:
  name: external-postgres-configuration-eda
  namespace: "{{ namespace_site_two }}"
data:
  database: "{{ db_name_eda }}"
  host: "{{ db_host_site_two }}"
  password: "{{ db_password_eda }}"
  port: "{{ db_port }}"
  sslmode: "{{ db_sslmode }}"
  type: unmanaged
  username: "{{ db_username_eda }}"
type: Opaque