kind: Secret
apiVersion: v1
metadata:
  name: external-postgres-configuration-controller
  namespace: aap-26
data:
  database: "{{ db_name_controller }}"
  host: "{{ db_host_site_two }}"
  password: "{{ db_password_controller }}"
  port: "{{ db_port }}"
  sslmode: "{{ db_sslmode }}"
  type: unmanaged
  username: "{{ db_username_controller }}"
type: Opaque